# Uncomment the next line to define a global platform for your project
 platform :ios, '15.2'

target 'MVPproject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Keychain'
  pod 'SwiftGen'
  pod 'GoogleMaps', '7.1.0'

  # Pods for MVPproject

  target 'MVPprojectMoke' do
    pod 'Keychain'
    pod 'GoogleMaps', '7.1.0'
  end
  
  target 'MVPprojectTests' do
    pod 'Keychain'
    pod 'GoogleMaps', '7.1.0'
  end
end

